name: Carzz Daily

on:
  schedule:
    - cron: '0 9 * * *'  # Run daily at 9:00 UTC
  workflow_dispatch:     # Optional manual run

jobs:
  api-flow:
    runs-on: ubuntu-latest

    env:
      IG_ACCESS_TOKEN: IGAAKnOFLpOHlBZAE5OOU1uVENOekE1SFl3U0Jta1BqSmJkTEJpejN5VzQtRlY5MGwwQkIxVHB3SFh3VTh3VlJjbHdkbUx4cGdGS3VmRGpPb0Vtc1pZAcFFCYktxVWxaVkM0QXdNR1d4ajBySHFiLVN0dndScldtN0I1VGJVMjJmTQZDZD

    steps:
      - name: Send POST request to get auth_id
        id: get_auth
        run: |
          BASE_DATE="2025-06-17"
          TODAY=$(date -u +"%Y-%m-%d")
          DAYS_DIFF=$(( ( $(date -d "$TODAY" +%s) - $(date -d "$BASE_DATE" +%s) ) / 86400 + 1 ))
          FILE_NUM=$(printf "%04d" $DAYS_DIFF)
          VIDEO_URL="https://github.com/thetga/reels_vids/raw/refs/heads/main/carzz/${FILE_NUM}.mp4"
          echo "video_url=$VIDEO_URL" >> $GITHUB_ENV
          RESPONSE=$(curl -s -X POST "https://graph.instagram.com/v23.0/17841474765092627/media" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $IG_ACCESS_TOKEN" \
            -d "{\"video_url\":\"$VIDEO_URL\", \"media_type\":\"REELS\", \"caption\":\"From 0 to legendary in seconds. #SpeedMeetsStyle #DreamMachine #NextLevelDrive #CarObsession #LuxuryDrive #CarPorn #AutoAddict #DriveInStyle\"}"

          echo "Full Response: $RESPONSE"
          AUTH_ID=$(echo "$RESPONSE" | jq -r '.id')
          echo "auth_id=$AUTH_ID" >> $GITHUB_ENV

      - name: Wait for 300 seconds before publishing
        run: sleep 300

      - name: Make GET request to publish media
        run: |
          curl -X GET "https://graph.instagram.com/v23.0/17841474765092627/media_publish?access_token=$IG_ACCESS_TOKEN&creation_id=${{ env.auth_id }}"
